# Глобальные настройки
TIMEOUT=5

# Имя записи (ОБЯЗАТЕЛЬНО начинается с '/')
/NovumOS
    # Используйте '=' для надежности
    PROTOCOL: multiboot2
    
    # Путь должен точно отражать структуру iso_root
    KERNEL_PATH: boot():/boot/kernel32.elf
    
    # Ваши параметры
    CMDLINE: quiet loglevel=3
