const kconfig = @import("kconfig.zig");

pub const k = kconfig;

pub const schema = [_]kconfig.Field{
    .{
        .name = "USE_GARBAGE_COLLECTOR",
        .default = .{ .bool = false },
        .help = "Build-time garbage collector support",
        .desc = "Enables automated garbage collection for kernel heap allocations. When enabled, dynamic memory uses tracking and collection passes to automatically reclaim unused allocations.",
    },
    .{
        .name = "HEAP_INITIAL_SIZE",
        .default = .{ .int = 1024 * 1024 },
        .help = "Initial kernel heap size (bytes)",
        .desc = "Specifies the initial contiguous physical memory size reserved for the kernel heap allocator at boot time. Default is 1048576 bytes (1 MiB). Increase this if memory allocations fail during early initialization.",
    },
    .{
        .name = "HISTORY_SIZE",
        .default = .{ .int = 50 },
        .help = "Shell command history buffer capacity",
        .desc = "Defines the maximum number of previously executed command lines stored in the interactive shell scrollback history buffer. Accessible via Up/Down arrow keys.",
    },
    .{
        .name = "ENABLE_DISK_HISTORY",
        .default = .{ .bool = true },
        .help = "Persist shell history to disk (.HISTORY)",
        .desc = "Saves shell command history to the .HISTORY file on the selected disk and restores it on boot. When disabled, history lives only in RAM and no disk reads or writes occur.",
    },
    .{
        .name = "ENABLE_DEBUG_CRASH_COMMANDS",
        .default = .{ .bool = false },
        .help = "Kernel crash test commands (panic, div0, pf)",
        .desc = "Enables intentional crash commands in the interactive shell (such as panic, div0, and pagefault) to test fault handling, stack unwinding, and kernel recovery routines.",
    },
    .{
        .name = "ENABLE_DEBUG_COMMANDS",
        .default = .{ .bool = true },
        .help = "Kernel inspection & debug shell commands",
        .desc = "Enables diagnostic shell utilities for inspecting CPU registers, memory mappings, GDT/IDT descriptors, and process execution state.",
    },
    .{
        .name = "ENABLE_EARLY_LFB_DEBUG",
        .default = .{ .bool = false },
        .help = "Early Linear Framebuffer (LFB) boot test pattern",
        .desc = "Draws a diagnostic color test pattern on the linear framebuffer immediately after Multiboot2 video info is obtained, verifying graphics mode switching before full console initialization.",
    },
    .{
        .name = "ENABLE_SERIAL_DEBUG",
        .default = .{ .bool = false },
        .help = "COM1 serial port logging (115200 8N1)",
        .desc = "Directs all low-level kernel log messages and register dumps to the primary serial port COM1 (0x3F8). Recommended when running inside QEMU with -serial stdio.",
    },
    .{
        .name = "ENABLE_IDT_WATCHDOG",
        .default = .{ .bool = true },
        .help = "Interrupt Descriptor Table (IDT) integrity watchdog",
        .desc = "Periodically validates the hardware IDT gates and descriptor addresses to detect stack corruptions or unauthorized descriptor modifications. Requires ENABLE_SYSENTER=y.",
    },
    .{
        .name = "ENABLE_IDT_WATCHDOG_SNAPSHOT",
        .default = .{ .bool = true },
        .help = "Save IDT snapshot at boot for later integrity comparison",
        .desc = "Takes a snapshot of the IDT at boot for the watchdog to compare against during runtime validation. Disable to save boot time if IDT watchdog is not used.",
    },
    .{
        .name = "ENABLE_RSOD_REBOOT",
        .default = .{ .bool = true },
        .help = "Automatic reboot after Red Screen of Death",
        .desc = "Enables automatic system reset after a kernel panic / Red Screen of Death crash screen is displayed. If disabled, the system will halt and remain on the crash screen.",
    },
    .{
        .name = "ENABLE_EMBEDDED_ELFS",
        .default = .{ .bool = false },
        .help = "Embed user-mode ELF binaries in kernel image",
        .desc = "Embeds precompiled static user ELF binaries directly into kernel read-only data sections so they can be launched without requiring an underlying disk filesystem.",
    },
    .{
        .name = "ENABLE_FAT_DEBUG",
        .default = .{ .bool = false },
        .help = "FAT12/16/32 filesystem debug logging",
        .desc = "Enables verbose diagnostic output during BPB parsing, FAT cluster traversal, directory entry lookups, and file read operations.",
    },
    .{
        .name = "ENABLE_KERNEL_LOGGING",
        .default = .{ .bool = false },
        .help = "Informational kernel ring buffer logging",
        .desc = "Enables the in-memory circular log ring buffer and formatted log levels (INFO, WARN, ERROR, DEBUG) for runtime inspection.",
    },
    .{
        .name = "ENABLE_BOOT_TRACE",
        .default = .{ .bool = false },
        .help = "Stage-by-stage boot trace (kmain to shell)",
        .desc = "Prints a timestamped marker for every boot stage from kmain entry through memory, drivers, disk, scheduler, SMP and the final Ring 3 shell handoff. Independent of ENABLE_KERNEL_LOGGING; enable when diagnosing early boot hangs.",
    },
    .{
        .name = "ENABLE_SYSCALL_TRACE",
        .default = .{ .bool = false },
        .help = "Log every user syscall (number, args, result)",
        .desc = "Prints one line per SYSENTER trap with the syscall number, argument registers (ebx/ecx/edx/esi) and the return value. Very verbose and slows the shell noticeably; enable only when tracing user/kernel interaction.",
    },
    .{
        .name = "ENABLE_SPEAKER",
        .default = .{ .bool = true },
        .help = "PC speaker audio hardware support",
        .desc = "Enables the motherboard PC speaker driver via PIT channel 2 (port 0x61/0x42) for acoustic tones and sound effects.",
    },
    .{
        .name = "ENABLE_BOOT_BEEP",
        .default = .{ .bool = true },
        .help = "Audible confirmation tone on boot",
        .desc = "Plays a short confirmation beep through the PC speaker when the kernel completes fundamental subsystem initialization.",
    },
    .{
        .name = "ENABLE_ERROR_BEEP",
        .default = .{ .bool = true },
        .help = "Audible alarm tone on kernel panics & errors",
        .desc = "Plays an acoustic warning pattern via the PC speaker when an unhandled exception, assertion failure, or kernel panic occurs.",
    },
    .{
        .name = "NOVA_PATH_POLICY_ENABLED",
        .default = .{ .bool = true },
        .help = "Nova path policy validation (CVE-2026-40573)",
        .desc = "Enforces strict canonical path checks and directory traversal mitigations in the Nova runtime to prevent CVE-2026-40573 security bypasses.",
    },
    .{
        .name = "NOVA_DEBUG",
        .default = .{ .bool = false },
        .help = "Nova VM & bytecode execution tracing",
        .desc = "Enables detailed instruction-level tracing, AST evaluation logs, and runtime memory allocation dumps for Nova language scripts.",
    },
    .{
        .name = "MOUSE_DEBUG",
        .default = .{ .bool = false },
        .help = "PS/2 mouse initialization & packet logs",
        .desc = "Prints raw byte packets, acknowledge responses, and IRQ12 interrupt delivery events during PS/2 auxiliary mouse setup.",
    },
    .{
        .name = "ENABLE_QUANTUM",
        .default = .{ .bool = true },
        .help = "Kernel quantum circuit simulation engine",
        .desc = "Enables the in-kernel quantum state vector simulator and quantum shell commands (qrun, qstate, qgate) for running quantum algorithms.",
    },
    .{
        .name = "ENABLE_DOOMFIRE",
        .default = .{ .bool = true },
        .help = "DOOM procedural fire visual demo command",
        .desc = "Enables the classic DOOM PSX procedural fire particle simulation effect in the graphical terminal console.",
    },
    .{
        .name = "ENABLE_MATRIX",
        .default = .{ .bool = true },
        .help = "Matrix rain visual demo command",
        .desc = "Enables the Matrix rain screensaver effect in the graphical terminal console.",
    },
    .{
        .name = "ENABLE_BUILTIN_SCRIPTS",
        .default = .{ .bool = true },
        .help = "Embedded Nova scripts (hello, syscheck)",
        .desc = "Includes built-in diagnostic and demo Nova scripts directly in the kernel image, accessible via the shell without mounting a disk.",
    },
    .{
        .name = "ENABLE_MOUSE",
        .default = .{ .bool = true },
        .help = "PS/2 mouse driver & cursor subsystem",
        .desc = "Enables the PS/2 mouse hardware driver, interrupt handler (IRQ12), coordinate tracking, and visual mouse cursor rendering.",
    },
    .{
        .name = "ENABLE_SMP",
        .default = .{ .bool = true },
        .help = "Symmetric Multiprocessing (SMP) multicore support",
        .desc = "Enables MADT table parsing, Local APIC setup, AP trampoline startup, inter-processor interrupts (IPIs), and multicore execution.",
    },
    .{
        .name = "ENABLE_NOVA",
        .default = .{ .bool = true },
        .help = "Nova programming language runtime environment",
        .desc = "Enables the core Nova language interpreter, memory runtime, embedded userspace ELF loader, and interactive scripting engine.",
    },
    .{
        .name = "ENABLE_FAT12",
        .default = .{ .bool = true },
        .help = "FAT12 filesystem driver support",
        .desc = "Enables mounting and formatting FAT12 volumes. When disabled, FAT12 disks are rejected by read_bpb and the mkfs-fat12 command disappears from help.",
    },
    .{
        .name = "ENABLE_FAT16",
        .default = .{ .bool = true },
        .help = "FAT16 filesystem driver support",
        .desc = "Enables mounting and formatting FAT16 volumes. When disabled, FAT16 disks are rejected by read_bpb and the mkfs-fat16 command disappears from help.",
    },
    .{
        .name = "ENABLE_FAT32",
        .default = .{ .bool = true },
        .help = "FAT32 filesystem driver support",
        .desc = "Enables mounting and formatting FAT32 volumes. When disabled, FAT32 disks are rejected by read_bpb and the mkfs-fat32 command disappears from help.",
    },
    .{
        .name = "ENABLE_LFN",
        .default = .{ .bool = true },
        .help = "Long filename (LFN) support",
        .desc = "Enables long filename entries (attr 0x0F). When disabled, only 8.3 short names work: LFN entries are skipped on lookup and adding a long name fails.",
    },
    .{
        .name = "ENABLE_SERIAL_INPUT",
        .default = .{ .bool = true },
        .help = "Serial port keyboard input (COM1)",
        .desc = "Enables reading keyboard input from the serial port (COM1 0x3F8) in addition to PS/2. Disable to remove serial polling overhead.",
    },
    .{
        .name = "ENABLE_VGA_TEXT",
        .default = .{ .bool = true },
        .help = "VGA text mode emulation layer",
        .desc = "Enables the VGA text emulation layer for the console. Disable to save code size if only LFB graphics mode is used.",
    },
    .{
        .name = "ENABLE_ACPI",
        .default = .{ .bool = true },
        .help = "ACPI power management (MADT/SMP, shutdown)",
        .desc = "Enables ACPI table parsing for SMP core discovery (MADT) and power-off (shutdown). Disable to remove ACPI code; SMP will be single-core and shutdown will halt instead of power-off.",
    },
    .{
        .name = "ENABLE_PCI",
        .default = .{ .bool = true },
        .help = "PCI bus enumeration & lspci command",
        .desc = "Enables PCI configuration space scanning and the lspci shell command. Disable to remove PCI driver code when no PCI devices need enumeration.",
    },
    .{
        .name = "ENABLE_ATA",
        .default = .{ .bool = true },
        .help = "ATA PIO disk driver and disk commands",
        .desc = "Enables the ATA PIO disk driver, disk probing at boot, and all disk-related shell commands (lsdsk, mount, mkfs, format). Disable for headless/RAM-only builds without disk support.",
    },
    .{
        .name = "ENABLE_CLOCK_IN_PROMPT",
        .default = .{ .bool = true },
        .help = "Live clock & serial mirror in shell prompt",
        .desc = "Enables the live HH:MM:SS clock update in the prompt, serial console mirroring of the command line, and cursor visibility on the serial port. Disable to reduce per-keypress overhead on minimal builds.",
    },
    .{
        .name = "ENABLE_STATUS_INDICATORS",
        .default = .{ .bool = true },
        .help = "CAPS/NUM/INS status indicators in top-right",
        .desc = "Enables CAPS, NUM, and INS lock status indicator letters drawn in the top-right corner of the screen on every prompt refresh.",
    },
    .{
        .name = "ENABLE_WELCOME_MESSAGE",
        .default = .{ .bool = true },
        .help = "Boot banner and welcome message",
        .desc = "Prints the NovumOS ASCII art banner and welcome message on boot. Disable for silent/headless boot.",
    },
    .{
        .name = "ENABLE_BOOT_SPINNER",
        .default = .{ .bool = true },
        .help = "Animated boot progress spinner during init",
        .desc = "Shows a spinning |/ -\\ animation during driver and disk initialization. Disable for minimal text output.",
    },
    .{
        .name = "ENABLE_ASLR",
        .default = .{ .bool = true },
        .help = "Address Space Layout Randomization (ASLR)",
        .desc = "Randomizes the load address of the kernel heap, stack, and Nova ELF at boot (x86-32 without PAE). Falls back to fixed addresses if entropy unavailable.",
    },
    .{
        .name = "ENABLE_WX_SEPARATION",
        .default = .{ .bool = true },
        .help = "Write-XOR-Execute separation via CS limit tightening",
        .desc = "Enforces W^X by tightening the code-segment limit to the exact kernel code size and using a separate data segment. Pages outside the code limit cause #GP → page fault on execute. Requires i686+ limit fault support.",
    },
};
